name: Medical Api CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up Go environment
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.19

      # Cache Go modules
      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ hashFiles('go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      # Install Go dependencies
      - name: Install dependencies
        run: go mod download

      # Run Linter (golangci-lint is used here, adjust based on your preference)
      - name: Lint code
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s v1.50.0
          ./bin/golangci-lint run

      # Run tests
      - name: Run tests
        run: go test -v ./...

      # Build the Go application
      - name: Build
        run: go build -v

      # Optionally, you can upload the build artifacts
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: go-fiber-app
          path: ./main
