# Build stage
FROM golang:1.19-alpine AS builder

WORKDIR /app

# Copy go mod and sum files
COPY go.mod go.sum ./

# Download all dependencies. Dependencies will be cached if the go.mod and go.sum files are not changed
RUN go mod download

# Copy the source code
COPY . .

# Build the Go app
RUN go build -o main .

# Final stage
FROM alpine:latest

WORKDIR /root/

# Copy the pre-built Go binary from the build stage
COPY --from=builder /app/main .

# Expose the port on which the app will run
EXPOSE 3000

# Run the Go app
CMD ["./main"]
